
import React, { useState } from 'react'; import { v4 as uuidv4 } from 'uuid'; import toast from 'react-hot-toast'; import { useProductionBatchStore } from '@/state/productionBatchStore'; import { ProductionBatch } from '@/types'; import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'; import { Label } from '@/components/ui/Label'; import { Input } from '@/components/ui/Input'; import { Button } from '@/components/ui/Button'; import { Textarea } from '@/components/ui/Textarea'; import { format } from 'date-fns'; import { Package, Plus } from 'lucide-react';
const ProductionBatchScreen: React.FC = () => {
  const { batches, addBatch } = useProductionBatchStore(); const [batchName, setBatchName] = useState(''); const [description, setDescription] = useState('');
  const handleAddBatch = async () => {
    if (!batchName.trim()) { toast.error('批次名称不能为空'); return; }
    const newBatch: ProductionBatch = { id: uuidv4(), name: batchName, description: description, createdAt: new Date().toISOString() };
    await fetch('/api/production-batches', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newBatch) });
    addBatch(newBatch); toast.success(`生产批次 "${batchName}" 已创建！`); setBatchName(''); setDescription('');
  };
  return <div className="animate-fade-in"><h1 className="page-header">生产批次管理</h1><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-1"><Card><CardHeader><CardTitle>创建新批次</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="batchName">批次名称</Label><Input id="batchName" value={batchName} onChange={(e) => setBatchName(e.target.value)} placeholder="例如：2024-05-21-A" /></div><div><Label htmlFor="description">批次描述 (可选)</Label><Textarea id="description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="例如：来自A生产线的首批产品" rows={3} /></div><Button onClick={handleAddBatch} className="w-full"><Plus className="mr-2 h-4 w-4" />创建批次</Button></CardContent></Card></div><div className="lg:col-span-2"><Card><CardHeader><CardTitle>现有批次列表</CardTitle></CardHeader><CardContent>{batches.length === 0 ? <p className="text-gray-500 text-center py-8">暂无生产批次。</p> : <div className="space-y-3 max-h-[60vh] overflow-y-auto">{batches.map((batch) => <div key={batch.id} className="flex items-start gap-4 p-3 border rounded-lg"><div className="bg-primary-100 p-2 rounded-full mt-1"><Package className="h-5 w-5 text-primary-600" /></div><div className="flex-grow"><p className="font-semibold">{batch.name}</p><p className="text-sm text-gray-600">{batch.description || '无描述'}</p><p className="text-xs text-gray-400 mt-1">创建于: {format(new Date(batch.createdAt || new Date()), 'yyyy-MM-dd HH:mm')}</p></div></div>)}</div>}</CardContent></Card></div></div></div>;
};
export default ProductionBatchScreen;
