
import React, { useState, useEffect, useCallback } from 'react'; import { Button } from '@/components/ui/Button'; import { Card, CardContent } from '@/components/ui/Card'; import { Input } from '@/components/ui/Input'; import { Label } from '@/components/ui/Label'; import { Textarea } from '@/components/ui/Textarea'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/Select'; import { Standard } from '@/types'; import toast from 'react-hot-toast'; import { v4 as uuidv4 } from 'uuid'; import { Trash2, PlusCircle } from 'lucide-react'; import { apiFetch } from '@/lib/config';
const StandardsScreen: React.FC = () => {
    const [standards, setStandards] = useState<Standard[]>([]); const [currentStandard, setCurrentStandard] = useState<Partial<Standard> | null>(null);
    const fetchStandards = useCallback(async () => { try { const res = await apiFetch('/standards'); if (!res.ok) throw new Error('无法获取标准模板'); setStandards(await res.json()); } catch (error) { toast.error(error instanceof Error ? error.message : '获取模板失败'); } }, []);
    useEffect(() => { fetchStandards(); }, [fetchStandards]);
    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault(); if (!currentStandard || !currentStandard.name || !currentStandard.type || !currentStandard.criteria) { toast.error('名称、类型和检测要求为必填项！'); return; }
        const toastId = toast.loading(currentStandard.id ? '正在更新...' : '正在保存...');
        try {
            const res = await apiFetch('/standards', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...currentStandard, id: currentStandard.id || uuidv4() }), });
            if (!res.ok) throw new Error('保存失败'); toast.success('保存成功！', { id: toastId }); setCurrentStandard(null); await fetchStandards();
        } catch (error) { toast.error(error instanceof Error ? error.message : '保存模板失败', { id: toastId }); }
    };
    const handleDelete = async (id: string) => {
        if (!window.confirm('确定要删除这个标准模板吗？')) return; const toastId = toast.loading('正在删除...');
        try { const res = await apiFetch(`/standards/${id}`, { method: 'DELETE' }); if (!res.ok) throw new Error('删除失败'); toast.success('删除成功！', { id: toastId }); if (currentStandard?.id === id) setCurrentStandard(null); await fetchStandards(); } catch (error) { toast.error(error instanceof Error ? error.message : '删除模板失败', { id: toastId }); }
    };
    return (
        <div className="animate-fade-in grid grid-cols-1 md:grid-cols-3 gap-6"><div className="md:col-span-1"><h1 className="page-header">模板列表</h1><Card><CardContent className="p-4"><Button onClick={() => setCurrentStandard({})} className="w-full mb-4"><PlusCircle className="mr-2 h-4 w-4" />创建新模板</Button><div className="space-y-2 max-h-[60vh] overflow-y-auto pr-2">{standards.map(s => <div key={s.id} onClick={() => setCurrentStandard(s)} className={`p-3 rounded-md cursor-pointer flex justify-between items-center transition-colors ${currentStandard?.id === s.id ? 'bg-secondary' : 'hover:bg-accent'}`}><span>{s.name}</span><Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); handleDelete(s.id); }}><Trash2 className="h-4 w-4 text-destructive/70 hover:text-destructive" /></Button></div>)}</div></CardContent></Card></div><div className="md:col-span-2">{currentStandard ? <div><h1 className="page-header">{currentStandard.id ? '编辑模板' : '创建新模板'}</h1><Card><CardContent className="p-6"><form onSubmit={handleSave} className="space-y-4"><div><Label htmlFor="name">模板名称</Label><Input id="name" value={currentStandard.name || ''} onChange={e => setCurrentStandard(p => ({ ...p, name: e.target.value }))} /></div><div><Label htmlFor="type">模板类型</Label><Select value={currentStandard.type} onValueChange={v => setCurrentStandard(p => ({ ...p, type: v as any }))}><SelectTrigger><SelectValue placeholder="选择类型..." /></SelectTrigger><SelectContent><SelectItem value="rule_based">基于规则</SelectItem><SelectItem value="image_based">基于图像</SelectItem></SelectContent></Select></div><div><Label htmlFor="criteria">检测要求</Label><Textarea rows={5} id="criteria" value={currentStandard.criteria || ''} onChange={e => setCurrentStandard(p => ({ ...p, criteria: e.target.value }))} /></div>{currentStandard.type === 'image_based' && <div><Label htmlFor="standardImage">标准样本图片 (Base64 URL)</Label><Textarea rows={3} id="standardImage" placeholder="粘贴图片的 Base64 Data URL..." value={currentStandard.standardImage || ''} onChange={e => setCurrentStandard(p => ({ ...p, standardImage: e.target.value }))} /></div>}<div><Label htmlFor="overrideSystemPrompt">覆盖系统提示词 (可选)</Label><Textarea rows={5} id="overrideSystemPrompt" placeholder="留空则使用全局系统提示词" value={currentStandard.overrideSystemPrompt || ''} onChange={e => setCurrentStandard(p => ({ ...p, overrideSystemPrompt: e.target.value }))} /></div><div className="flex gap-4"><Button type="submit" className="w-full">保存模板</Button><Button type="button" variant="secondary" className="w-full" onClick={() => setCurrentStandard(null)}>取消</Button></div></form></CardContent></Card></div> : <div className="flex items-center justify-center h-full text-muted-foreground"><p>← 从左侧选择一个模板进行编辑，或创建一个新模板。</p></div>}</div></div>
    );
};
export default StandardsScreen;
