# OBS -> Jetson RTMP ingest.
# OBS server: rtmp://<JETSON_IP>/live
# OBS stream key: obs
rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        ping 10s;
        ping_timeout 20s;

        application live {
            live on;
            record off;
            idle_streams off;
            drop_idle_publisher 30s;
        }
    }
}
