# Generated by Django 4.2.23 on 2025-09-01 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('compression_enabled', models.BooleanField(default=False)),
                ('compression_quality', models.IntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='DefectSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#FF0000', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('severity_levels', models.JSONField(default=list)),
                ('color', models.CharField(default='#FF00FF', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('criteria', models.TextField(blank=True, default='')),
                ('standard_image', models.ImageField(blank=True, null=True, upload_to='standards/')),
                ('send_standard_image', models.BooleanField(default=False)),
                ('override_system_prompt', models.TextField(blank=True, null=True)),
                ('defect_types', models.TextField(blank=True, default='', help_text='JSON string of defect type configurations')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='results/')),
                ('overall_quality', models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('需复检', '需复检')], max_length=10)),
                ('score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('reason_keywords', models.TextField(blank=True, null=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.standard')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#00FFFF', max_length=16)),
                ('defect_types', models.JSONField(default=list, help_text='List of defect type names')),
                ('severity_threshold', models.CharField(default='一般', max_length=20)),
                ('importance', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='中', max_length=4)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_areas', to='inspection.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('轻微', '轻微'), ('一般', '一般'), ('严重', '严重'), ('致命', '致命')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('area_id', models.UUIDField(blank=True, null=True)),
                ('inspection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspection.inspectionresult')),
            ],
        ),
    ]
