# Generated by Django 4.2.23 on 2025-09-01 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(default='production', help_text='部署环境', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', '待部署'), ('DEPLOYING', '部署中'), ('ACTIVE', '已激活'), ('FAILED', '部署失败'), ('STOPPED', '已停止')], default='PENDING', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='部署配置')),
                ('resources', models.JSONField(default=dict, help_text='资源配置')),
                ('deployed_by', models.CharField(blank=True, help_text='部署人员', max_length=100)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=0, help_text='请求次数')),
                ('error_count', models.IntegerField(default=0, help_text='错误次数')),
                ('avg_response_time', models.FloatField(default=0.0, help_text='平均响应时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模型名称', max_length=255)),
                ('version', models.CharField(help_text='版本号', max_length=50)),
                ('model_type', models.CharField(choices=[('PPE_YOLO', 'PPE YOLO检测模型'), ('YOLO_GENERAL', '通用YOLO模型'), ('CUSTOM', '自定义模型')], default='PPE_YOLO', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '激活'), ('DEPRECATED', '已弃用'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('model_file', models.FileField(help_text='模型文件', upload_to='models/')),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小(字节)')),
                ('file_hash', models.CharField(blank=True, help_text='文件哈希值', max_length=64)),
                ('description', models.TextField(blank=True, help_text='模型描述')),
                ('author', models.CharField(blank=True, help_text='作者', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='标签列表')),
                ('accuracy', models.FloatField(blank=True, help_text='准确率', null=True)),
                ('precision', models.FloatField(blank=True, help_text='精确率', null=True)),
                ('recall', models.FloatField(blank=True, help_text='召回率', null=True)),
                ('f1_score', models.FloatField(blank=True, help_text='F1分数', null=True)),
                ('framework_version', models.CharField(blank=True, help_text='框架版本', max_length=50)),
                ('input_shape', models.CharField(blank=True, help_text='输入形状', max_length=100)),
                ('output_shape', models.CharField(blank=True, help_text='输出形状', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModelUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='文件名', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='文件大小')),
                ('upload_progress', models.IntegerField(default=0, help_text='上传进度(0-100)')),
                ('status', models.CharField(choices=[('UPLOADING', '上传中'), ('VALIDATING', '验证中'), ('SUCCESS', '上传成功'), ('FAILED', '上传失败')], default='UPLOADING', max_length=20)),
                ('uploaded_by', models.CharField(blank=True, help_text='上传人员', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validation_result', models.JSONField(default=dict, help_text='验证结果')),
                ('error_message', models.TextField(blank=True, help_text='错误信息')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.modelversion')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(help_text='响应时间(ms)')),
                ('memory_usage', models.FloatField(help_text='内存使用(MB)')),
                ('cpu_usage', models.FloatField(help_text='CPU使用率(%)')),
                ('gpu_usage', models.FloatField(blank=True, help_text='GPU使用率(%)', null=True)),
                ('request_count', models.IntegerField(default=1, help_text='请求次数')),
                ('success_count', models.IntegerField(default=1, help_text='成功次数')),
                ('error_count', models.IntegerField(default=0, help_text='错误次数')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='inspection.modeldeployment')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='inspection.modelversion')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='modeldeployment',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='inspection.modelversion'),
        ),
    ]
