# Generated by Django 4.2.23 on 2025-09-18 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_modeldeployment_modelversion_modelupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('PPE_YOLO', 'PPE YOLO检测模型'), ('YOLO_GENERAL', '通用YOLO模型'), ('FILTER_CORE', '滤芯检测模型'), ('CUSTOM', '自定义模型')], help_text='模型类型', max_length=20, unique=True)),
                ('current_model_id', models.CharField(help_text='当前激活的模型ID', max_length=100)),
                ('model_config', models.JSONField(default=dict, help_text='模型配置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_type'],
            },
        ),
    ]
