# Generated by Django 4.2.23 on 2025-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_modelconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
