# Generated by Django 4.2.23 on 2025-09-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_alter_inspectionresult_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='user_message',
            field=models.TextField(blank=True, default='', help_text='用户消息模板'),
        ),
    ]
