# Generated by Django 4.2.23 on 2025-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_aiconfig_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionresult',
            name='detection_type',
            field=models.CharField(choices=[('cleanroom_ppe', '洁净用品检测'), ('standard_inspection', '标准检测'), ('general_quality', '通用质量检测'), ('unknown', '未知类型')], default='unknown', help_text='检测类型', max_length=20),
        ),
    ]
