# Generated by Django 4.2.23 on 2025-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0008_add_ocr_llm_result_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionresult",
            name="llm_full_text",
            field=models.TextField(
                blank=True, help_text="LLM返回的完整文字", null=True
            ),
        ),
    ]
