# Generated by Django 4.2.23 on 2025-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0009_inspectionresult_llm_full_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionresult",
            name="llm_full_detail",
            field=models.JSONField(
                blank=True, help_text="详细结果结构化JSON", null=True
            ),
        ),
    ]
