# Generated by Django 4.2.25 on 2025-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_inspectionresult_llm_full_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresult',
            name='detection_type',
            field=models.CharField(choices=[('cleanroom_ppe', '洁净用品检测'), ('standard_inspection', '标准检测'), ('general_quality', '通用质量检测'), ('ocr_inspection', 'OCR检测'), ('ocr_fusion_inspection', 'OCR融合检测'), ('kit_matching', '齐套化检测'), ('unknown', '未知类型')], default='unknown', help_text='检测类型', max_length=25),
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='overall_quality',
            field=models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('需复检', '需复检'), ('存疑', '存疑')], max_length=10),
        ),
    ]
