# Generated by Django 4.2.25 on 2025-11-12 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_alter_inspectionresult_detection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='流媒体名称', max_length=255)),
                ('url', models.CharField(help_text='流媒体地址', max_length=1024)),
                ('stream_type', models.CharField(choices=[('rtsp', 'RTSP流'), ('rtmp', 'RTMP流'), ('http', 'HTTP流'), ('file', '本地文件'), ('hls', 'HLS流')], default='rtsp', max_length=20)),
                ('status', models.CharField(choices=[('inactive', '未激活'), ('active', '激活中'), ('error', '错误'), ('connecting', '连接中')], default='inactive', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('auto_reconnect', models.BooleanField(default=True, help_text='自动重连')),
                ('reconnect_interval', models.IntegerField(default=5, help_text='重连间隔(秒)')),
                ('username', models.CharField(blank=True, default='', help_text='用户名', max_length=255)),
                ('password', models.CharField(blank=True, default='', help_text='密码', max_length=255)),
                ('last_connected_at', models.DateTimeField(blank=True, help_text='最后连接时间', null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='最后错误信息')),
                ('error_count', models.IntegerField(default=0, help_text='错误次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '流媒体源',
                'verbose_name_plural': '流媒体源',
                'ordering': ['-created_at'],
            },
        ),
    ]
