# Generated by Django 4.2.25 on 2025-11-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_streamsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsource',
            name='play_mode',
            field=models.CharField(choices=[('png', 'PNG模式 (低CPU占用，低延迟)'), ('ffmpeg', 'FFmpeg模式 (高画质，高CPU占用)')], default='png', help_text='播放模式', max_length=20),
        ),
    ]
