# Generated by Django 4.2.25 on 2025-11-12 15:18

from django.db import migrations, models


def update_png_to_jpg(apps, schema_editor):
    """更新现有的 'png' 值为 'jpg'"""
    StreamSource = apps.get_model('inspection', 'StreamSource')
    StreamSource.objects.filter(play_mode='png').update(play_mode='jpg')


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0013_streamsource_play_mode'),
    ]

    operations = [
        migrations.RunPython(update_png_to_jpg, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='streamsource',
            name='play_mode',
            field=models.CharField(choices=[('jpg', 'JPEG模式 (低CPU占用，低延迟)'), ('ffmpeg', 'FFmpeg模式 (高画质，高CPU占用)')], default='jpg', help_text='播放模式', max_length=20),
        ),
    ]
