# Generated by Django 4.2.25 on 2025-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_change_png_to_jpg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamsource',
            name='play_mode',
            field=models.CharField(choices=[('jpg', 'PNG模式 (无损画质，低CPU占用，低延迟)'), ('ffmpeg', 'FFmpeg模式 (备选方案，高CPU占用)')], default='jpg', help_text='播放模式', max_length=20),
        ),
    ]
