# Generated by Django 4.2.25 on 2025-11-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0015_alter_streamsource_play_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamsource',
            name='play_mode',
            field=models.CharField(choices=[('jpg', 'JPG模式 (无压缩画质，低CPU占用，低延迟)'), ('ffmpeg', 'FFmpeg模式 (备选方案，高CPU占用)')], default='ffmpeg', help_text='播放模式', max_length=20),
        ),
    ]
