# Generated by Django 4.2.25 on 2025-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0016_alter_streamsource_play_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='model_type',
            field=models.CharField(choices=[('PPE_YOLO', 'PPE YOLO检测模型'), ('YOLO_GENERAL', '通用YOLO模型'), ('FILTER_CORE', '滤芯检测模型'), ('WATER_PURIFIER', '净水机模型')], help_text='模型类型', max_length=20, unique=True),
        ),
    ]
