# Generated by Django 4.2.25 on 2025-11-13 05:51

from django.db import migrations


def update_custom_to_water_purifier(apps, schema_editor):
    """将现有的CUSTOM类型更新为WATER_PURIFIER"""
    ModelConfig = apps.get_model('inspection', 'ModelConfig')
    # 更新所有model_type为'CUSTOM'的记录
    ModelConfig.objects.filter(model_type='CUSTOM').update(model_type='WATER_PURIFIER')
    print("✅ 已将CUSTOM类型更新为WATER_PURIFIER")


def reverse_update(apps, schema_editor):
    """回滚：将WATER_PURIFIER改回CUSTOM"""
    ModelConfig = apps.get_model('inspection', 'ModelConfig')
    ModelConfig.objects.filter(model_type='WATER_PURIFIER').update(model_type='CUSTOM')
    print("✅ 已将WATER_PURIFIER类型回滚为CUSTOM")


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0017_change_custom_to_water_purifier'),
    ]

    operations = [
        migrations.RunPython(update_custom_to_water_purifier, reverse_update),
    ]
