# Generated by Django 4.2.25 on 2025-11-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0018_update_custom_to_water_purifier_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelupload',
            name='model_file',
            field=models.FileField(blank=True, help_text='模型文件（.pt格式）', null=True, upload_to='uploads/models/'),
        ),
    ]
