# Generated by Django 4.2.25 on 2025-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0019_add_model_file_to_model_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='类别英文名称（如：name_MCF, service_label）', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('names', '名称类'), ('labels', '标签类'), ('logos', 'Logo类'), ('others', '其他类')], default='others', help_text='分类', max_length=20)),
                ('chinese_name', models.CharField(blank=True, help_text='中文名称（可选，如果为空则从model_config.py获取）', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='显示顺序（数字越小越靠前）')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('description', models.TextField(blank=True, help_text='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '检测类别分类',
                'verbose_name_plural': '检测类别分类',
                'ordering': ['category', 'display_order', 'class_name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='inspection__categor_bd90f7_idx'), models.Index(fields=['class_name'], name='inspection__class_n_4a68cd_idx')],
            },
        ),
    ]
