# Generated by Django 4.2.25 on 2025-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0020_add_class_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcategory',
            name='category',
            field=models.CharField(choices=[('names', '名称类'), ('labels', '标签类'), ('logos', 'Logo类'), ('ppe', '劳保类'), ('materials', '材质类'), ('components', '组件类'), ('features', '特征类'), ('others', '其他类')], default='others', help_text='分类', max_length=20),
        ),
    ]
