# Generated by Django 4.2.23 on 2025-11-21 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0022_add_barcode_result_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRBarcodeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模板名称', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='模板描述或备注')),
                ('barcode_configs', models.JSONField(blank=True, default=list, help_text='二维码配置列表')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', help_text='创建人', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OCR二维码模板',
                'verbose_name_plural': 'OCR二维码模板',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRKeywordTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模板名称', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='模板描述或备注')),
                ('keywords', models.TextField(blank=True, default='', help_text='原始关键词字符串（逗号分隔）')),
                ('keyword_configs', models.JSONField(blank=True, default=list, help_text='关键词配置列表')),
                ('match_mode', models.CharField(choices=[('contains', '包含'), ('exact', '完全匹配')], default='contains', max_length=20)),
                ('min_confidence', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', help_text='创建人', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OCR关键词模板',
                'verbose_name_plural': 'OCR关键词模板',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
