# Generated by Django 4.2.25 on 2025-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0023_ocrbarcodetemplate_ocrkeywordtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconfig',
            options={'verbose_name': 'AI配置', 'verbose_name_plural': 'AI配置'},
        ),
        migrations.AlterModelOptions(
            name='defect',
            options={'verbose_name': '缺陷记录', 'verbose_name_plural': '缺陷记录'},
        ),
        migrations.AlterModelOptions(
            name='defectseverity',
            options={'verbose_name': '缺陷严重等级', 'verbose_name_plural': '缺陷严重等级'},
        ),
        migrations.AlterModelOptions(
            name='defecttype',
            options={'verbose_name': '缺陷类型', 'verbose_name_plural': '缺陷类型'},
        ),
        migrations.AlterModelOptions(
            name='inspectionarea',
            options={'verbose_name': '检测区域', 'verbose_name_plural': '检测区域'},
        ),
        migrations.AlterModelOptions(
            name='inspectionresult',
            options={'verbose_name': '检测结果', 'verbose_name_plural': '检测结果'},
        ),
        migrations.AlterModelOptions(
            name='modelconfig',
            options={'ordering': ['model_type'], 'verbose_name': '模型配置', 'verbose_name_plural': '模型配置'},
        ),
        migrations.AlterModelOptions(
            name='modeldeployment',
            options={'ordering': ['-created_at'], 'verbose_name': '模型部署', 'verbose_name_plural': '模型部署'},
        ),
        migrations.AlterModelOptions(
            name='modelperformance',
            options={'ordering': ['-timestamp'], 'verbose_name': '模型性能', 'verbose_name_plural': '模型性能'},
        ),
        migrations.AlterModelOptions(
            name='modelupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '模型上传', 'verbose_name_plural': '模型上传'},
        ),
        migrations.AlterModelOptions(
            name='modelversion',
            options={'ordering': ['-created_at'], 'verbose_name': '模型版本', 'verbose_name_plural': '模型版本'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': '检测标准', 'verbose_name_plural': '检测标准'},
        ),
    ]
