# Generated by Django 4.2.25 on 2025-12-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0024_alter_aiconfig_options_alter_defect_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresult',
            name='detection_type',
            field=models.CharField(choices=[('cleanroom_ppe', '洁净用品检测'), ('standard_inspection', '标准检测'), ('general_quality', '通用质量检测'), ('ocr_inspection', 'OCR检测'), ('ocr_fusion_inspection', 'OCR融合检测'), ('kit_matching', '齐套化检测'), ('unknown', '未知类型')], db_index=True, default='unknown', help_text='检测类型', max_length=25),
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='overall_quality',
            field=models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('需复检', '需复检'), ('存疑', '存疑')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='inspectionresult',
            index=models.Index(fields=['detection_type', 'timestamp'], name='inspection__detecti_bc1ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionresult',
            index=models.Index(fields=['overall_quality', 'timestamp'], name='inspection__overall_881056_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionresult',
            index=models.Index(fields=['-timestamp'], name='inspection__timesta_7eca86_idx'),
        ),
    ]
