# Generated by Django 4.2.25 on 2025-12-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0025_alter_inspectionresult_detection_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inspectionresult',
            name='inspection__detecti_bc1ec7_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspectionresult',
            name='inspection__overall_881056_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspectionresult',
            name='inspection__timesta_7eca86_idx',
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='detection_type',
            field=models.CharField(choices=[('cleanroom_ppe', '洁净用品检测'), ('standard_inspection', '标准检测'), ('general_quality', '通用质量检测'), ('ocr_inspection', 'OCR检测'), ('ocr_fusion_inspection', 'OCR融合检测'), ('kit_matching', '齐套化检测'), ('unknown', '未知类型')], default='unknown', help_text='检测类型', max_length=25),
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='overall_quality',
            field=models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('需复检', '需复检'), ('存疑', '存疑')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
