# Generated by Django 4.2.25 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0026_remove_inspectionresult_inspection__detecti_bc1ec7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionresult',
            name='business_code',
            field=models.CharField(blank=True, default='', help_text='当前工序业务编码', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='business_code_type',
            field=models.CharField(blank=True, default='', help_text='业务编码类型', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='camera_id',
            field=models.CharField(blank=True, default='', help_text='相机ID', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_qr',
            field=models.CharField(blank=True, default='', help_text='工装板二维码', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_qr_confidence',
            field=models.FloatField(blank=True, help_text='工装二维码识别置信度', null=True),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_qr_detected',
            field=models.BooleanField(default=False, help_text='是否识别到工装二维码'),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_qr_input_status',
            field=models.CharField(blank=True, default='', help_text='工装二维码输入状态', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_qr_source',
            field=models.CharField(blank=True, default='', help_text='工装二维码来源', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_rule_passed',
            field=models.BooleanField(blank=True, help_text='工装规则是否通过', null=True),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_rule_reason',
            field=models.TextField(blank=True, default='', help_text='工装规则说明'),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='page_instance_id',
            field=models.CharField(blank=True, default='', help_text='页面实例ID', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='process_stage_code',
            field=models.CharField(blank=True, default='', help_text='工序标识', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='process_stage_name',
            field=models.CharField(blank=True, default='', help_text='工序名称', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='related_stages',
            field=models.JSONField(blank=True, default=list, help_text='已关联工序', null=True),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='trace_conclusion',
            field=models.CharField(blank=True, default='', help_text='追踪结论', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='trace_conclusion_reason',
            field=models.TextField(blank=True, default='', help_text='追踪结论说明'),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='trace_context',
            field=models.JSONField(blank=True, default=dict, help_text='追踪上下文', null=True),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='trace_rule_details',
            field=models.JSONField(blank=True, default=list, help_text='规则明细', null=True),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='trace_rule_summary',
            field=models.TextField(blank=True, default='', help_text='规则摘要'),
        ),
        migrations.AddIndex(
            model_name='inspectionresult',
            index=models.Index(fields=['fixture_qr'], name='inspection__fixtur_e949c8_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionresult',
            index=models.Index(fields=['fixture_qr', 'process_stage_code'], name='inspection__fixtur_942f63_idx'),
        ),
    ]
