# Generated by Django 4.2.25 on 2026-03-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0027_add_trace_fields_to_inspectionresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inspectionresult',
            new_name='inspection__fixture_387e39_idx',
            old_name='inspection__fixtur_e949c8_idx',
        ),
        migrations.RenameIndex(
            model_name='inspectionresult',
            new_name='inspection__fixture_f091ef_idx',
            old_name='inspection__fixtur_942f63_idx',
        ),
    ]
