# Generated by Django 4.2.23 on 2026-03-16 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0028_rename_inspection__fixtur_e949c8_idx_inspection__fixture_387e39_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRecipeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('process_stage_code', models.CharField(blank=True, default='', max_length=100)),
                ('process_stage_name', models.CharField(blank=True, default='', max_length=255)),
                ('fixture_qr_prefixes', models.CharField(blank=True, default='', max_length=500)),
                ('fixture_qr_pattern', models.CharField(blank=True, default='', max_length=500)),
                ('camera_id', models.CharField(blank=True, default='', max_length=100)),
                ('enable_keyword_analysis', models.BooleanField(default=False)),
                ('keywords', models.TextField(blank=True, default='')),
                ('keyword_configs', models.JSONField(blank=True, default=list)),
                ('keyword_match_mode', models.CharField(default='contains', max_length=20)),
                ('min_confidence', models.FloatField(default=0.5)),
                ('enable_barcode_detection', models.BooleanField(default=False)),
                ('barcode_configs', models.JSONField(blank=True, default=list)),
                ('ocr_engine_model', models.CharField(default='auto', max_length=20)),
                ('detection_confidence', models.FloatField(default=0.7)),
                ('fusion_mode_enabled', models.BooleanField(default=False)),
                ('selected_standard_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': '工序配方模版',
                'verbose_name_plural': '工序配方模版',
                'ordering': ['-updated_at'],
            },
        ),
    ]
