# Generated by Django 4.2.23 on 2026-03-16 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0029_stagerecipetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(max_length=20)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', '待处理'), ('suspended', '挂起'), ('in_progress', '处理中'), ('resolved', '已关闭'), ('escalated', '已升级'), ('scrapped', '已报废')], default='open', max_length=20)),
                ('process_stage_code', models.CharField(blank=True, default='', max_length=100)),
                ('fixture_qr', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_snapshot', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=100)),
                ('synced', models.BooleanField(default=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_records', to='inspection.stagerecipetemplate')),
                ('related_results', models.ManyToManyField(blank=True, related_name='anomaly_records', to='inspection.inspectionresult')),
            ],
            options={
                'verbose_name': '异常记录',
                'verbose_name_plural': '异常记录',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('process_stage_code', models.CharField(blank=True, default='', max_length=100)),
                ('anomaly_type', models.CharField(choices=[('consecutive_fail', '连续不合格'), ('batch_anomaly', '批量异常'), ('trace_break', '追踪断裂'), ('timeout', '超时未检'), ('critical_defect', '关键缺陷')], max_length=20)),
                ('severity', models.CharField(choices=[('warning', '警告'), ('critical', '严重'), ('emergency', '紧急')], default='warning', max_length=20)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('auto_escalate_minutes', models.IntegerField(blank=True, help_text='超时未处理自动升级(分钟)', null=True)),
                ('password_suspend', models.CharField(default='password', max_length=255)),
                ('password_resolve', models.CharField(default='password', max_length=255)),
                ('password_escalate', models.CharField(default='password', max_length=255)),
                ('password_scrap', models.CharField(default='password', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_notify_url', models.URLField(blank=True, default='')),
                ('external_notify_payload_template', models.JSONField(blank=True, default=dict)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_rules', to='inspection.stagerecipetemplate')),
            ],
            options={
                'verbose_name': '异常规则',
                'verbose_name_plural': '异常规则',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('suspend', '挂起'), ('resume', '恢复'), ('resolve', '关闭'), ('escalate', '升级'), ('scrap', '报废'), ('comment', '备注')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('operator', models.CharField(blank=True, default='', max_length=100)),
                ('password_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='inspection.anomalyrecord')),
            ],
            options={
                'verbose_name': '异常处理记录',
                'verbose_name_plural': '异常处理记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anomalyrecord',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='inspection.anomalyrule'),
        ),
        migrations.AddIndex(
            model_name='anomalyrule',
            index=models.Index(fields=['anomaly_type', 'is_active'], name='inspection__anomaly_8d2ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyrule',
            index=models.Index(fields=['process_stage_code'], name='inspection__process_768159_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyrecord',
            index=models.Index(fields=['status', 'anomaly_type'], name='inspection__status_50d4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyrecord',
            index=models.Index(fields=['process_stage_code', 'status'], name='inspection__process_735218_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyrecord',
            index=models.Index(fields=['fixture_qr'], name='inspection__fixture_d8f6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyrecord',
            index=models.Index(fields=['opened_at'], name='inspection__opened__144153_idx'),
        ),
    ]
