# Generated by Django 4.2.23 on 2026-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0030_anomalyrecord_anomalyrule_anomalyresolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='current_model_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='selected_targets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
