# Generated by Django 4.2.25 on 2026-03-16 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0031_stagerecipetemplate_current_model_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='产品配方名称', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='描述')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': '产品配方',
                'verbose_name_plural': '产品配方',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, help_text='工序顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stage_links', to='inspection.productrecipe')),
                ('stage_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stage_links', to='inspection.stagerecipetemplate')),
            ],
            options={
                'verbose_name': '产品工序关联',
                'verbose_name_plural': '产品工序关联',
                'ordering': ['order', 'created_at'],
                'unique_together': {('product_recipe', 'stage_recipe', 'order')},
            },
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='stages',
            field=models.ManyToManyField(help_text='关联的工序配方列表', related_name='product_recipes', through='inspection.ProductStage', to='inspection.stagerecipetemplate'),
        ),
    ]
