# Generated by Django 4.2.25 on 2026-03-16 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0032_productrecipe_productstage_productrecipe_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='工装名称', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('prefixes', models.CharField(blank=True, default='', help_text='码前缀(逗号分隔)', max_length=500)),
                ('pattern', models.CharField(blank=True, default='', help_text='正则表达式', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工装模板',
                'verbose_name_plural': '工装模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='fixture_template',
            field=models.ForeignKey(blank=True, help_text='关联的工装模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='inspection.fixturetemplate'),
        ),
    ]
