# Generated by Django 4.2.23 on 2026-03-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0033_fixturetemplate_stagerecipetemplate_fixture_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstage',
            name='stage_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stage_links', to='inspection.stagerecipetemplate'),
        ),
    ]
