# Generated by Django 4.2.23 on 2026-03-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0034_productstage_protect_stage_recipe_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='auto_capture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='batch_apply_rules',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='batch_processing_mode',
            field=models.CharField(default='batch', max_length=20),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='capture_delay_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='compression_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='compression_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='detection_interval',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='image_save_mode',
            field=models.CharField(default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='qr_detect_interval_seconds',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='roi_weight_ratio',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='yolo_detection_mode',
            field=models.CharField(default='or', max_length=10),
        ),
        migrations.AddField(
            model_name='stagerecipetemplate',
            name='yolo_timeout_seconds',
            field=models.FloatField(default=-1),
        ),
    ]
