# Generated by Django 4.2.25 on 2026-03-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0037_add_target_confidences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagerecipetemplate',
            name='device_action_map',
            field=models.JSONField(blank=True, default=dict, help_text='检测结果→设备指令映射 {"alarm":{"qualified":"GREEN\\n","unqualified":"RED\\n","idle":"OFF\\n"}}'),
        ),
        migrations.AlterField(
            model_name='stagerecipetemplate',
            name='required_device_types',
            field=models.JSONField(blank=True, default=list, help_text='必需设备类型 ["alarm","scanner"]'),
        ),
        migrations.AlterField(
            model_name='stagerecipetemplate',
            name='target_confidences',
            field=models.JSONField(blank=True, default=dict, help_text='每个目标独立置信度覆盖 {"防伪标签":0.8,"条码标签":0.5}'),
        ),
    ]
