# Generated by Django 4.2.23 on 2026-03-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0038_add_fixture_enabled'),
        ('inspection', '0038_alter_stagerecipetemplate_device_action_map_and_more'),
    ]

    operations = [
    ]
