# Generated by Django 4.2.23 on 2026-03-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0039_add_non_grid_targets'),
        ('inspection', '0039_merge_20260318_1507'),
    ]

    operations = [
    ]
