# Generated by Django 4.2.23 on 2026-03-19 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0040_merge_20260318_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstage',
            name='is_fqc',
            field=models.BooleanField(default=False, help_text='是否为FQC（终检）工序'),
        ),
        migrations.CreateModel(
            name='FQCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixture_qr', models.CharField(help_text='工装板二维码', max_length=255)),
                ('product_recipe_name', models.CharField(blank=True, default='', help_text='产品配方名称快照', max_length=255)),
                ('fqc_stage_code', models.CharField(blank=True, default='', help_text='触发FQC的工序标识', max_length=100)),
                ('fqc_stage_name', models.CharField(blank=True, default='', help_text='触发FQC的工序名称', max_length=100)),
                ('overall_result', models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('存疑', '存疑')], default='存疑', max_length=10)),
                ('result_reason', models.TextField(blank=True, default='', help_text='汇总结论说明')),
                ('stage_summary', models.JSONField(blank=True, default=list, help_text='各工序检验摘要 [{stageCode, stageName, resultId, quality, timestamp, businessCode}]')),
                ('trace_flow', models.JSONField(blank=True, default=list, help_text='工装板流转记录 [{stageCode, stageName, timestamp, operator, quality}]')),
                ('trace_conclusion', models.CharField(blank=True, default='', help_text='追踪总结论', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fqc_records', to='inspection.productrecipe')),
                ('related_inspections', models.ManyToManyField(blank=True, related_name='fqc_records', to='inspection.inspectionresult')),
                ('trigger_result', models.ForeignKey(blank=True, help_text='触发FQC的检验记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fqc_trigger', to='inspection.inspectionresult')),
            ],
            options={
                'verbose_name': 'FQC终检记录',
                'verbose_name_plural': 'FQC终检记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fixture_qr'], name='inspection__fixture_598447_idx'), models.Index(fields=['fixture_qr', 'product_recipe'], name='inspection__fixture_0cde3f_idx')],
            },
        ),
    ]
