# Generated by Django 4.2.23 on 2026-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0041_fqc_record_and_is_fqc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqcrecord',
            name='validation_details',
            field=models.JSONField(blank=True, default=list, help_text='规则校验明细 [{ruleName, passed, expected, actual, message}]'),
        ),
        migrations.AddField(
            model_name='fqcrecord',
            name='validation_passed',
            field=models.BooleanField(blank=True, help_text='规则校验是否通过（null=未启用校验）', null=True),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='fqc_validation_enabled',
            field=models.BooleanField(default=False, help_text='是否启用FQC规则校验'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='fqc_validation_rules',
            field=models.JSONField(blank=True, default=list, help_text='FQC校验规则列表'),
        ),
    ]
