# Generated by Django 4.2.27 on 2026-09-09 01:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0043_add_turntable_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureLoadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixture_qr', models.CharField(help_text='工装板二维码', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='轮次结束时间（FQC完成或被新轮次替换）', null=True)),
            ],
            options={
                'verbose_name': '工装装载会话',
                'verbose_name_plural': '工装装载会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='fixture_session',
            field=models.ForeignKey(blank=True, help_text='工装装载会话（同一装载轮次共享，FQC只汇总本轮记录）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_results', to='inspection.fixtureloadsession'),
        ),
        migrations.AddIndex(
            model_name='inspectionresult',
            index=models.Index(fields=['fixture_session', 'process_stage_code'], name='inspection__fixture_f8e0df_idx'),
        ),
        migrations.AddField(
            model_name='fqcrecord',
            name='fixture_session',
            field=models.ForeignKey(blank=True, help_text='装载会话（每轮独立终检记录，A07）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fqc_records', to='inspection.fixtureloadsession'),
        ),
        migrations.AddIndex(
            model_name='fixtureloadsession',
            index=models.Index(fields=['fixture_qr', 'closed_at'], name='inspection__fixture_278d9d_idx'),
        ),
    ]
